#define ERROR_STR_INVALIDINPUT		"Function input is invalid."
#define ERROR_STR_INVALIDSIGNATURE	"OpenSSL signature is invalid."
#define ERROR_STR_INVALIDSIGNATURE2	"OpenSSL signature is invalid Error code is %lu."
#define ERROR_STR_HASHERROR			"Hash functions error occured."
#define ERROR_STR_STRINGLISTERROR	"String list functions error occured."
#define ERROR_STR_ZIPERROR			"ZIP operation error: %s"
#define ERROR_STR_INVALIDTIME		"Time structure is invalid."
#define ERROR_STR_INVALIDSTRING		"String is invalid."
#define ERROR_STR_INVALIDXML		"XML object is invalid."
#define ERROR_STR_INVALIDBASE64		"BASE64 hash is invalid."
#define ERROR_STR_FILEFAIL			"File operation failed."
#define ERROR_STR_INITIALIZATION	"Initialization error."
#define ERROR_STR_CONFIGURATION		"Configuration error."
#define ERROR_STR_SIGNALHANDLER		"Cannot set signal handler."
#define ERROR_STR_LIBCURL			"libCURL error ocurred: %s."
#define ERROR_STR_SOAP				"SOAP method \"%s\" error occured."
#define ERROR_STR_TOOLONG			"SOAP communication is timed out."
#define ERROR_STR_INVALIDHTTP		"HTTP error occured: %ld."
#define ERROR_STR_SMTPCONTEXT		"SMTP context is invalid."
#define ERROR_STR_SMTPFINISHED		"SMTP transmission finished."
#define ERROR_STR_NFQUEUE			"Cannot bind to netfilter queue %d."
#define ERROR_STR_INVALIDPACKET		"Netfilter received invalid network packet."
#define ERROR_STR_PTHREAD			"NFQ thread error occured."
#define ERROR_STR_NSERROR			"Name service request error occured."
#define ERROR_STR_IPSET1			"Register information has not been applied."
#define ERROR_STR_IPSET2			"Register information has been applied."
#define ERROR_STR_SOCKETERROR		"Error occured during socket operation."
#define ERROR_STR_MONITORING		"Cannot start monitoring thread."
#define ERROR_STR_STOPRECONF		"STOP OR RECONFIGURE while processing register information."
#define ERROR_STR_CUSTOMBL			"Custom blacklist is invalid."
